### ISSUE TITLE
Dot indexing is not supported for variables of this type & query regarding multiple file processing

### ISSUE THREAD

**Issue by imeMFK01** [Brain-Connectivity-Lab/Preprocessing_and_QC#1]
Dear @dixy0 

Really wonderful for creating this utility. I have a couple of questions for running this.

**Question 1:** I have a *.dcm file so for providing as an input to the file "Q1a_MRI_information.m". I have converted this file into *.nii using below SPM options once the file is converted and after providing path into the above mentioned code file I am receiving the following error (**Error 1**).

Run SPM using MATLAB Command Window
Menu > Batch Editor > DICOM files (click) > DICOM files (navigate and select the files) > Done (click)
Menu > Batch Editor > Output directory (navigate and select the directory)
Menu > Batch Editor > Conversion options  .Output image format > Single file (nii) NIfTI > Batch Editor  (click Run Batch green button)

**Error 1:**

tr(subji,1) = v_func(1).private.timing.tspace
Dot indexing is not supported for variables of this type.

Error in nifti/subsref>rec (line 221)
            t = subsref(t,subs(2:end));

Error in indexing (line 45)
varargout = rec(opt,subs);

**Question 2:** My dataset contains 404 files for each subject so how can I cater this using the code files (Q1a_MRI_information.m, Q1b_anat_check.m, and Q1c_func_check.m)?

If you have any query then please feel free to ask.

Looking forward to hearing from you.

Thanks.

**Comment by dixy0** [comment]
Hi @imeMFK01,
Thank you for your interest in this project. 
I think you might need to convert your .dcm data into Nifti format first (*.nii). If they were converted correctly, the header file should contain the filed .timing.tspace. But I am not sure whether it is true for all the data. 
I am currently working on providing sample images for the project. Unfortunately, I am encountering issues with GitHub's limitations on uploading large files. I am working to find a solution to this problem.
Best, 
Xin

**Comment by imeMFK01** [comment]
Thank you very much for the kind explanation.
